baseURL = "https://aoudiamoncef.github.io"
languageCode = "en-us"
title = "Moncef AOUDIA"
theme = "bilberry"
copyright = "Copyright © 2021 Moncef AOUDIA"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

enableGitInfo = true

enableEmoji = true

googleAnalytics = ""

[outputs]
  home = [ "HTML", "JSON", "AMP", "RSS" ]
  page = [ "HTML", "AMP"]

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
  [markup.asciidocExt]
    backend = "html5"
    extensions = ["asciidoctor-html5s"]
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = true
    trace = false
    verbose = false
    workingFolderCurrent = false

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  publishDate = ["publishDate", "date", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]

defaultContentLanguage = "en"
