name: Build and deploy to Github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install asciidoctor asciidoctor-html5s

      - name: Run Hugo
        run: |
          alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
          hugo --minify --verbose

      - name: Upload Hugo Algolia Index
        uses: aoudiamoncef/hugo-algolia-uploader@main
        with:
          app_id: ${{ secrets.ALGOLIA_APP_ID }}
          admin_key: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          index_name: ${{ secrets.ALGOLIA_INDEX_NAME }}
          index_languages: fr

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
